### ISSUE TITLE
[Feature request] Dark theme

### ISSUE THREAD

**Issue by parkerlreed** [Secretmapper/combustion#31]
Love the web UI but it's in dire need of a dark makeover. Is there any easy way to do this without having to manually edit the colors?

**Comment by Secretmapper** [comment]
Unfortunately combustion in it's current state does not support a dark mode. I am looking to revisit this package soon and will take note of this feature.

**Comment by djgamerr** [comment]
```css
.index__container___izEfr, .index__footer___mv3bv{
  filter:invert(1);
}
.index__header___28Tp8{
  background-color:rgb(45, 45, 48) !important;
}
.theme__drawer___1sAOY{
  filter:invert(1);
}
.theme__dialog___3lw90{
  background-color:#bfbfbf !important;
  filter:invert(1);
  color:white;
}
.theme__label___34120{
  color:black !important;
}
```

Here you go, add it to "main.css" next to index.html, its a cheap and dirty dark mode :)
