### ISSUE TITLE
Install via docker, not working

### ISSUE THREAD

**Issue by justdayan** [Secretmapper/combustion#32]
Greetings,

I've just put a plain vanilla ubuntu 18.04 server up in Digital Ocean. Unfortunately, none of your instructions are working.

Here's what I did:

---

sudo apt update && sudo apt upgrade -y

sudo apt install docker.io docker-compose -y

git clone https://github.com/Secretmapper/combustion.git

cd combustion/

sudo docker build -t combustion .

#This successfull gets me a build

#Successfully built 8dabfe418292
#Successfully tagged combustion:latest

#But as you can see, when I run your next command, it doesn't work
---

~/code/combustion$ sudo docker run -d --restart=always -p 80:80 --link some-transmission container combustion
Unable to find image 'container:latest' locally
docker: Error response from daemon: pull access denied for container, repository does not exist or may require 'docker login'.
See 'docker run --help'.

~/code/combustion$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

---

It would be great if the docker build was tested, and the instructions were updated. This doesn't work.

Thank you advance.

JD

**Comment by meliurwen** [comment]
I see you're using compose, I don't have followed their steps, for my istance I've simply done this:
+ Mounted a volume dedicated to themes inside the transmission's container
+ Unzipped [this](https://github.com/Secretmapper/combustion/archive/release.zip) inside the volume just created
+ Added the environment variable `TRANSMISSION_WEB_HOME` and pointed it to the theme folder

For reference my `docker-compose.yml` file is something _similar_ to this:
```
version: '3'

services:
  transmission:
    build: .
    restart: unless-stopped
    volumes:
      - <local_path_to_themes_folder>:<docker_path_to_themes_folder>
    ports:
      - "51413:51413"
    expose:
      - "9091"
    environment:
      TRANSMISSION_WEB_HOME: "<docker_path_to_themes_folder>/combustion-release"
```
